version: '3.7'

services:
  reverseproxy:
    image: nginx
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro

  jupyter-server:
    image: jupyter/scipy-notebook
    ports:
      - 3181:8888